const reco = [
    {
        id: 1,
        name : "Préférence Blondes",
        price: "12.20€",
        categ: "blond",
        img: "/images/hairProducts/teinture_blond1.png",
    },
    {
        id: 2,
        name : "Excellence Crème Blondes",
        price: "11.70€",
        categ: "blond",
        img: "/images/hairProducts/teinture_blond2.png",
    },
    {
        id: 3,
        name : "Casting Crème Gloss Blondes",
        price: "10.90€",
        categ: "blond",
        img: "/images/hairProducts/teinture_blond3.png",
    },
    {
        id: 4,
        name : "Préférence CHÂTAIN",
        price: "11.90€",
        categ: "DarkBlond",
        img: "/images/hairProducts/teinture_chatain1.png",
    },
    {
        id: 5,
        name : "Excellence Crème CHÂTAIN",
        price: "11.70€",
        categ: "DarkBlond",
        img: "/images/hairProducts/teinture_chatain2.png",
    },
    {
        id: 6,
        name : "CASTING CRÈME GLOSS CHÂTAIN",
        price: "10.90€",
        categ: "DarkBlond",
        img: "/images/hairProducts/teinture_chatain3.png",
    },
    {
        id: 7,
        name : "EXCELLENCE CRÈME REFLETS",
        price: "11.50€",
        categ: "red",
        img: "/images/hairProducts/teinture_roux3.png",
    },
    {
        id: 8,
        name : "CASTING CRÈME GLOSS BRUNES / NOIRES",
        price: "10.80€",
        categ: "brown",
        img: "/images/hairProducts/teinture_brun1.png",
    },
    {
        id: 9,
        name : "EXCELLENCE CRÈME BRUNES / NOIRES",
        price: "11.70€",
        categ: "brown",
        img: "/images/hairProducts/teinture_brun2.png",
    },
    {
        id: 10,
        name : "EXCELLENCE CRÈME UNIVERSAL NUDES - LES BRUNS",
        price: "11.90€",
        categ: "brown",
        img: "/images/hairProducts/teinture_brun3.png",
    },
    {
        id: 11,
        name : "PRÉFÉRENCE REFLETS",
        price: "11.90€",
        categ: "red",
        img: "/images/hairProducts/teinture_roux2.png",
        
    },
    {
        id: 12,
        name : "CASTING CRÈME GLOSS REFLETS",
        price: "10.90€",
        categ: "red",
        img: "/images/hairProducts/teinture_roux1.png",
    },
    {
        id: 13,
        name : "MASQUE VIOLET DÉMÊLANT DÉJAUNISSEUR",
        price: "6.19€",
        categ: "soin",
        img: "/images/hairProducts/soin_cheveux2.png",
    },
    {
        id: 14,
        name : "ELSEVE COLOR-VIVE SHAMPOING VIOLET DÉJAUNISSEUR",
        price: "4.14€",
        categ: "soin",
        img: "/images/hairProducts/soin_cheveux1.png",
    },
    {
        id: 15,
        name : "ELSEVE TOTAL REPAIR 5 CICA REPAIR",
        price: "7.50€",
        categ: "soin",
        img: "/images/hairProducts/soin_cheveux3.png",
    },
    {
        id: 16,
        name : "ELSEVE HUILE-EN-CRÈME CHEVEUX TRÈS SECS OU FRISÉS",
        price: "7.50€",
        categ: "soin",
        img: "/images/hairProducts/soin_cheveux4.png",
    },

];

export default reco;
